FROM ubuntu:16.04

MAINTAINER gcsekar@gmail.com	

# Install bash
RUN apt-get -y update && apt-get -y upgrade
RUN chown -R root /usr/lib
RUN apt-get install -y curl && apt-get install -y wget
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
RUN apt-get install -y nodejs
RUN npm install -g angular
#RUN chown -r root /usr/lib/node_modules/@angular/
RUN npm install -g @angular/cli

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
RUN chown -R root /usr/src/app

COPY package.json /usr/src/app
RUN npm install
# If you are building your code for production
# RUN sudo npm install --only=production
COPY . /usr/src/app

EXPOSE 4200
CMD ["ng","serve","--host","0.0.0.0"]
